//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "addon_detail")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub description: Option<String>,
    pub change_log: Option<String>,
    pub version: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::addon::Entity",
        from = "Column::Id",
        to = "super::addon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Addon,
}

impl Related<super::addon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Addon.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
