//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "addon_dependency")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub addon_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub dependency_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::addon::Entity",
        from = "Column::DependencyId",
        to = "super::addon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Addon2,
    #[sea_orm(
        belongs_to = "super::addon::Entity",
        from = "Column::AddonId",
        to = "super::addon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Addon1,
}

impl ActiveModelBehavior for ActiveModel {}
