//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub mod prelude;

pub mod addon;
pub mod addon_dependency;
pub mod addon_detail;
pub mod addon_dir;
pub mod addon_image;
pub mod category;
pub mod category_parent;
pub mod game_compatibility;
pub mod installed_addon;
pub mod manual_dependency;
